### PR TITLE
adding link to github in website footer

### PR DESCRIPTION
**Pull request by benvanwerkhoven**
Fixes issue #80

### CODE REVIEW

**Review by knarrff — COMMENTED** [review]
Even if all the unnecessary social links might not be configured and thus, might not effectively be used, I would feel better if we only include the lines that handle github here, not Facebook & co as well.

**Comment by sdruskat** [comment]
I've simplified the addition of the link (although the theme-included icon now got lost). @knarrff Is that better? @benvanwerkhoven Are you okay with these changes? If so, feel free to merge (and fix #80).

**Comment by benvanwerkhoven** [comment]
Sure, I just copied the footer from the latest version of the minima template, but this is also fine. Thanks!

**Comment by sdruskat** [comment]
Thanks @benvanwerkhoven!

**Pull request merged**
