### PR TITLE
Update content for 2nd intl RSE day

### PR DESCRIPTION
**Pull request by sdruskat**
This PR updates the website content for 2nd Intl. RSE Day.

Council member associations should push to this branch (`update-intl-rse-day-info`) to update their respective info by the end of the week (*7 October*) I think, to get the info out in time.

### CODE REVIEW

**Comment by sdruskat** [comment]
@StephanJanosch Please feel free to update de-RSE entry to something more useful.

**Comment by StephanJanosch** [comment]
please use that pad URL: https://pad.gwdg.de/44b79pTvSYae9QEr8c5Dhw @sdruskat

**Comment by danielskatz** [comment]
In addition to adding new events, I feel like we should keep a record of the old events, not just delete them.

**Review by danielskatz — APPROVED** [review]

**Comment by sdruskat** [comment]
Thanks @danielskatz, I'll merge tomorrow as announced in case other items are being added in the meantime.

**Comment by paopao74cn** [comment]
The Digital Research Alliance of Canada (Alliance, Canada): will publicize the hashtag #IntlRSEday across Alliance's social platforms.

**Pull request merged**
